# start a standlone bundler for testing.
# bring up a the bundler with its own geth instance

version: '3'

services:
  bundler:
    image: maven:3.8.7-openjdk-18-slim
    platform: linux/amd64
    ports:
      - '3000:3000'
    env_file:
      - test.env
    working_dir: /app
    volumes:
      - ./:/app/
      - ./.m2/:/root/.m2/
    entrypoint: [ "sh", "-c", "mvn -s ./settings.xml clean package && java -jar ./aa-starter/target/aa-starter-0.0.1.jar" ]

    depends_on:
      eth-node:
        condition: service_started

  eth-node:
    container_name: geth-dev
    platform: linux/amd64
    ports: [ '8545:8545' ]
    image: ethereum/client-go:release-1.10
    command: --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api personal,eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --networkid 1337
      --dev
      --dev.period 0
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev.gaslimit 20000000

